db:
  repository: ghcr.io/aquasecurity/trivy-db
java-db:
  repository: ghcr.io/aquasecurity/trivy-java-db





  docker_build:
    runs-on: ubuntu-latest
    needs: build_test_coverage
    steps:
      - uses: actions/checkout@v4

      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Verify downloaded jar
        run: |
          set -euo pipefail
          ls -lah build/libs
          test -n "$(ls -1 build/libs/*.jar 2>/dev/null | head -n 1)" || (echo "❌ No llegó el jar" && exit 1)

      - name: Read Gradle version
        id: ver
        run: |
          set -euo pipefail
          VERSION=$(./gradlew -q printVersion | tr -d '\r' | tail -n 1)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Gradle version: $VERSION"

      - name: Build Docker image
        run: |
          set -euo pipefail
          IMAGE_NAME=ms-factura
          VERSION="${{ steps.ver.outputs.version }}"
          docker build -t $IMAGE_NAME:$VERSION .
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

      - name: Docker scan (Trivy) - fail on HIGH/CRITICAL
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ms-factura:${{ steps.ver.outputs.version }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          scanners: vuln
          trivy-config: .trivy.yaml

      - name: Show images
        run: docker images | head -n 50